/*
  # Add First Aid Kit module

  1. New Module
    - Insert First Aid Kit module with comprehensive content
    - Set appropriate difficulty level and badge information
    - Include structured slide-based content

  2. Content Structure
    - Multiple slides with navigation
    - Clear sections for different aspects of first aid kits
    - Prominent disclaimer at the end
*/

INSERT INTO modules (title, description, content, difficulty, badge_name, duration, icon) VALUES
(
  'First Aid Kit Essentials',
  'Learn what to include in your first aid kit and how to maintain it properly for emergency preparedness.',
  '{
    "slides": [
      {
        "id": 1,
        "title": "What is a First Aid Kit?",
        "content": "<div class=\"slide-content\"><h2>What is a First Aid Kit?</h2><p class=\"text-lg mb-6\">A first aid kit is a collection of supplies and equipment that is used to give medical treatment in case of an emergency or injury.</p><div class=\"bg-teal-50 border-l-4 border-teal-400 p-4 mb-6\"><p class=\"text-teal-800\"><strong>Key Purpose:</strong> To provide immediate care until professional medical help arrives</p></div><ul class=\"space-y-3 text-gray-700\"><li class=\"flex items-start\"><span class=\"text-teal-600 mr-2\">•</span>Treats minor injuries and wounds</li><li class=\"flex items-start\"><span class=\"text-teal-600 mr-2\">•</span>Helps stabilize serious conditions</li><li class=\"flex items-start\"><span class=\"text-teal-600 mr-2\">•</span>Provides tools for emergency response</li><li class=\"flex items-start\"><span class=\"text-teal-600 mr-2\">•</span>Gives confidence to help others</li></ul></div>"
      },
      {
        "id": 2,
        "title": "Essential Items for Your Kit",
        "content": "<div class=\"slide-content\"><h2>Essential Items for Your First Aid Kit</h2><p class=\"text-lg mb-6\">Every first aid kit should contain these fundamental supplies:</p><div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\"><div class=\"bg-white border border-gray-200 rounded-lg p-4\"><h3 class=\"font-bold text-teal-800 mb-3\">🩹 Wound Care</h3><ul class=\"space-y-2 text-sm\"><li>• Adhesive bandages (various sizes)</li><li>• Sterile gauze pads</li><li>• Medical tape</li><li>• Antiseptic wipes</li><li>• Antibiotic ointment</li></ul></div><div class=\"bg-white border border-gray-200 rounded-lg p-4\"><h3 class=\"font-bold text-teal-800 mb-3\">🧤 Protection & Tools</h3><ul class=\"space-y-2 text-sm\"><li>• Disposable gloves</li><li>• Scissors</li><li>• Tweezers</li><li>• Thermometer</li><li>• Emergency blanket</li></ul></div><div class=\"bg-white border border-gray-200 rounded-lg p-4\"><h3 class=\"font-bold text-teal-800 mb-3\">💊 Medications</h3><ul class=\"space-y-2 text-sm\"><li>• Pain relievers (ibuprofen, acetaminophen)</li><li>• Antihistamine</li><li>• Aspirin (for heart attack)</li><li>• Personal medications</li><li>• Burn gel</li></ul></div><div class=\"bg-white border border-gray-200 rounded-lg p-4\"><h3 class=\"font-bold text-teal-800 mb-3\">📋 Emergency Info</h3><ul class=\"space-y-2 text-sm\"><li>• Emergency contact numbers</li><li>• Medical information cards</li><li>• First aid instruction booklet</li><li>• Pen and paper</li><li>• Emergency cash</li></ul></div></div></div>"
      },
      {
        "id": 3,
        "title": "Kit Locations & Accessibility",
        "content": "<div class=\"slide-content\"><h2>Where to Keep Your First Aid Kits</h2><p class=\"text-lg mb-6\">Strategic placement ensures quick access when emergencies happen:</p><div class=\"space-y-6\"><div class=\"bg-yellow-50 border border-yellow-200 rounded-lg p-4\"><h3 class=\"font-bold text-teal-800 mb-3\">🏠 Home Kit Locations</h3><ul class=\"space-y-2\"><li class=\"flex items-start\"><span class=\"text-yellow-600 mr-2\">•</span><strong>Kitchen:</strong> Most accidents happen here</li><li class=\"flex items-start\"><span class=\"text-yellow-600 mr-2\">•</span><strong>Bathroom:</strong> Central, accessible location</li><li class=\"flex items-start\"><span class=\"text-yellow-600 mr-2\">•</span><strong>Master bedroom:</strong> For nighttime emergencies</li><li class=\"flex items-start\"><span class=\"text-yellow-600 mr-2\">•</span><strong>Garage/workshop:</strong> For tool-related injuries</li></ul></div><div class=\"bg-blue-50 border border-blue-200 rounded-lg p-4\"><h3 class=\"font-bold text-teal-800 mb-3\">🚗 Portable Kits</h3><ul class=\"space-y-2\"><li class=\"flex items-start\"><span class=\"text-blue-600 mr-2\">•</span><strong>Car:</strong> For travel emergencies</li><li class=\"flex items-start\"><span class=\"text-blue-600 mr-2\">•</span><strong>Workplace:</strong> Office or job site</li><li class=\"flex items-start\"><span class=\"text-blue-600 mr-2\">•</span><strong>Sports bag:</strong> For athletic activities</li><li class=\"flex items-start\"><span class=\"text-blue-600 mr-2\">•</span><strong>Travel kit:</strong> Compact for trips</li></ul></div><div class=\"bg-red-50 border border-red-200 rounded-lg p-4\"><h3 class=\"font-bold text-teal-800 mb-3\">⚠️ Accessibility Tips</h3><ul class=\"space-y-2\"><li class=\"flex items-start\"><span class=\"text-red-600 mr-2\">•</span>Keep kits in cool, dry places</li><li class=\"flex items-start\"><span class=\"text-red-600 mr-2\">•</span>Avoid extreme temperatures</li><li class=\"flex items-start\"><span class=\"text-red-600 mr-2\">•</span>Make sure everyone knows locations</li><li class=\"flex items-start\"><span class=\"text-red-600 mr-2\">•</span>Keep away from small children</li></ul></div></div></div>"
      },
      {
        "id": 4,
        "title": "Maintenance & Expiration",
        "content": "<div class=\"slide-content\"><h2>Keeping Your Kit Ready</h2><p class=\"text-lg mb-6\">Regular maintenance ensures your first aid kit is always ready when needed:</p><div class=\"space-y-6\"><div class=\"bg-green-50 border border-green-200 rounded-lg p-6\"><h3 class=\"font-bold text-teal-800 mb-4 flex items-center\"><span class=\"text-2xl mr-2\">📅</span>Monthly Checks</h3><ul class=\"space-y-3\"><li class=\"flex items-start\"><span class=\"text-green-600 mr-2\">✓</span>Check expiration dates on medications</li><li class=\"flex items-start\"><span class=\"text-green-600 mr-2\">✓</span>Replace used or damaged items</li><li class=\"flex items-start\"><span class=\"text-green-600 mr-2\">✓</span>Ensure all containers are sealed</li><li class=\"flex items-start\"><span class=\"text-green-600 mr-2\">✓</span>Update emergency contact information</li></ul></div><div class=\"bg-orange-50 border border-orange-200 rounded-lg p-6\"><h3 class=\"font-bold text-teal-800 mb-4 flex items-center\"><span class=\"text-2xl mr-2\">⏰</span>Expiration Guidelines</h3><div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\"><div><h4 class=\"font-semibold mb-2\">Replace Every 1-2 Years:</h4><ul class=\"text-sm space-y-1\"><li>• Adhesive bandages</li><li>• Antiseptic wipes</li><li>• Antibiotic ointment</li><li>• Burn gel</li></ul></div><div><h4 class=\"font-semibold mb-2\">Check Regularly:</h4><ul class=\"text-sm space-y-1\"><li>• Pain medications</li><li>• Antihistamines</li><li>• Thermometer batteries</li><li>• Emergency blanket</li></ul></div></div></div><div class=\"bg-blue-50 border border-blue-200 rounded-lg p-4\"><h3 class=\"font-bold text-teal-800 mb-3\">💡 Pro Tips</h3><ul class=\"space-y-2 text-sm\"><li>• Set phone reminders for monthly checks</li><li>• Keep receipts to track purchase dates</li><li>• Rotate stock - use older items first</li><li>• Consider seasonal additions (sunscreen, insect repellent)</li></ul></div></div></div>"
      },
      {
        "id": 5,
        "title": "Special Considerations",
        "content": "<div class=\"slide-content\"><h2>Customizing Your First Aid Kit</h2><p class=\"text-lg mb-6\">Tailor your kit to meet specific needs and situations:</p><div class=\"space-y-6\"><div class=\"bg-purple-50 border border-purple-200 rounded-lg p-4\"><h3 class=\"font-bold text-teal-800 mb-3\">👨‍👩‍👧‍👦 Family Considerations</h3><ul class=\"space-y-2\"><li class=\"flex items-start\"><span class=\"text-purple-600 mr-2\">•</span><strong>Infants:</strong> Baby thermometer, infant pain reliever</li><li class=\"flex items-start\"><span class=\"text-purple-600 mr-2\">•</span><strong>Children:</strong> Colorful bandages, child-safe scissors</li><li class=\"flex items-start\"><span class=\"text-purple-600 mr-2\">•</span><strong>Elderly:</strong> Magnifying glass, extra medications</li><li class=\"flex items-start\"><span class=\"text-purple-600 mr-2\">•</span><strong>Pets:</strong> Separate pet first aid supplies</li></ul></div><div class=\"bg-teal-50 border border-teal-200 rounded-lg p-4\"><h3 class=\"font-bold text-teal-800 mb-3\">🏃‍♂️ Activity-Specific Additions</h3><div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\"><div><h4 class=\"font-semibold mb-2\">Outdoor Activities:</h4><ul class=\"text-sm space-y-1\"><li>• Insect repellent</li><li>• Sunscreen</li><li>• Snake bite kit</li><li>• Emergency whistle</li></ul></div><div><h4 class=\"font-semibold mb-2\">Sports & Exercise:</h4><ul class=\"text-sm space-y-1\"><li>• Instant cold packs</li><li>• Elastic bandages</li><li>• Sports tape</li><li>• Electrolyte packets</li></ul></div></div></div><div class=\"bg-red-50 border border-red-200 rounded-lg p-4\"><h3 class=\"font-bold text-teal-800 mb-3\">🏥 Medical Conditions</h3><ul class=\"space-y-2\"><li class=\"flex items-start\"><span class=\"text-red-600 mr-2\">•</span><strong>Allergies:</strong> EpiPen, antihistamines</li><li class=\"flex items-start\"><span class=\"text-red-600 mr-2\">•</span><strong>Diabetes:</strong> Glucose tablets, insulin supplies</li><li class=\"flex items-start\"><span class=\"text-red-600 mr-2\">•</span><strong>Heart conditions:</strong> Prescribed medications</li><li class=\"flex items-start\"><span class=\"text-red-600 mr-2\">•</span><strong>Asthma:</strong> Rescue inhaler</li></ul></div></div></div>"
      },
      {
        "id": 6,
        "title": "Using Your Kit Effectively",
        "content": "<div class=\"slide-content\"><h2>How to Use Your First Aid Kit</h2><p class=\"text-lg mb-6\">Knowing how to properly use your supplies is just as important as having them:</p><div class=\"space-y-6\"><div class=\"bg-yellow-50 border border-yellow-200 rounded-lg p-6\"><h3 class=\"font-bold text-teal-800 mb-4 flex items-center\"><span class=\"text-2xl mr-2\">🚨</span>Emergency Response Steps</h3><ol class=\"space-y-3\"><li class=\"flex items-start\"><span class=\"bg-teal-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold mr-3 mt-0.5\">1</span><strong>Assess the situation</strong> - Ensure scene safety</li><li class=\"flex items-start\"><span class=\"bg-teal-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold mr-3 mt-0.5\">2</span><strong>Call for help</strong> - Dial 911 if needed</li><li class=\"flex items-start\"><span class=\"bg-teal-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold mr-3 mt-0.5\">3</span><strong>Protect yourself</strong> - Wear gloves</li><li class=\"flex items-start\"><span class=\"bg-teal-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold mr-3 mt-0.5\">4</span><strong>Provide care</strong> - Use appropriate supplies</li><li class=\"flex items-start\"><span class=\"bg-teal-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold mr-3 mt-0.5\">5</span><strong>Monitor</strong> - Watch for changes</li></ol></div><div class=\"bg-blue-50 border border-blue-200 rounded-lg p-4\"><h3 class=\"font-bold text-teal-800 mb-3\">🧤 Safety First</h3><ul class=\"space-y-2\"><li class=\"flex items-start\"><span class=\"text-blue-600 mr-2\">•</span>Always wear gloves when treating wounds</li><li class=\"flex items-start\"><span class=\"text-blue-600 mr-2\">•</span>Dispose of used materials properly</li><li class=\"flex items-start\"><span class=\"text-blue-600 mr-2\">•</span>Wash hands before and after treatment</li><li class=\"flex items-start\"><span class=\"text-blue-600 mr-2\">•</span>Never reuse single-use items</li></ul></div><div class=\"bg-green-50 border border-green-200 rounded-lg p-4\"><h3 class=\"font-bold text-teal-800 mb-3\">📚 Knowledge is Key</h3><ul class=\"space-y-2\"><li class=\"flex items-start\"><span class=\"text-green-600 mr-2\">•</span>Take a first aid course</li><li class=\"flex items-start\"><span class=\"text-green-600 mr-2\">•</span>Practice using your supplies</li><li class=\"flex items-start\"><span class=\"text-green-600 mr-2\">•</span>Read instruction manuals</li><li class=\"flex items-start\"><span class=\"text-green-600 mr-2\">•</span>Stay updated on best practices</li></ul></div></div></div>"
      },
      {
        "id": 7,
        "title": "Important Disclaimer",
        "content": "<div class=\"slide-content\"><div class=\"bg-red-100 border-2 border-red-400 rounded-lg p-8 mb-8\"><div class=\"flex items-center mb-4\"><span class=\"text-4xl mr-4\">⚠️</span><h2 class=\"text-2xl font-bold text-red-800\">Important Medical Disclaimer</h2></div><div class=\"space-y-4 text-red-800\"><p class=\"text-lg font-semibold\">This information is for educational purposes only and should not replace professional medical advice, diagnosis, or treatment.</p><ul class=\"space-y-3 text-base\"><li class=\"flex items-start\"><span class=\"text-red-600 mr-2 font-bold\">•</span><strong>Always seek professional medical help</strong> for serious injuries or medical emergencies</li><li class=\"flex items-start\"><span class=\"text-red-600 mr-2 font-bold\">•</span><strong>Call 911 immediately</strong> for life-threatening situations</li><li class=\"flex items-start\"><span class=\"text-red-600 mr-2 font-bold\">•</span><strong>First aid is temporary care</strong> until professional help arrives</li><li class=\"flex items-start\"><span class=\"text-red-600 mr-2 font-bold\">•</span><strong>Get proper training</strong> from certified first aid instructors</li><li class=\"flex items-start\"><span class=\"text-red-600 mr-2 font-bold\">•</span><strong>Know your limitations</strong> - never attempt procedures beyond your training</li></ul><p class=\"text-base font-medium bg-red-200 p-3 rounded border-l-4 border-red-600\">BeReady provides educational content only. We are not responsible for any actions taken based on this information. Always consult healthcare professionals for medical advice.</p></div></div><div class=\"text-center bg-teal-50 border border-teal-200 rounded-lg p-6\"><h3 class=\"text-xl font-bold text-teal-800 mb-4\">Ready to Test Your Knowledge?</h3><p class=\"text-gray-700 mb-6\">Complete the assessment to earn your First Aid Kit Essentials badge and demonstrate your understanding of proper kit preparation and maintenance.</p><div class=\"text-center\"><a href=\"#test\" class=\"inline-block bg-yellow-400 text-teal-800 px-8 py-4 rounded-lg text-lg font-bold hover:bg-yellow-300 transition-colors duration-200 shadow-lg\">Take the Test to Earn Your Badge</a></div></div></div>"
      }
    ]
  }',
  'beginner',
  'First Aid Kit Essentials',
  '15 min',
  '🧰'
);